In [1]:
try:
  %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf
print(tf.__version__)

2.2.0-rc1


In [0]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [0]:
sentences=["i like football.",
           "manchester united is the club that i support.",
           "football is life."]


In [0]:
MAX_VOCAB_SIZE = 20000
tokenizer = Tokenizer(num_words=MAX_VOCAB_SIZE)
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)

In [5]:
print(sequences)

[[1, 4, 2], [5, 6, 3, 7, 8, 9, 1, 10], [2, 3, 11]]


In [6]:
tokenizer.word_index

{'club': 8,
 'football': 2,
 'i': 1,
 'is': 3,
 'life': 11,
 'like': 4,
 'manchester': 5,
 'support': 10,
 'that': 9,
 'the': 7,
 'united': 6}

In [9]:
data = pad_sequences(sequences, padding='post')
print(data)

[[ 1  4  2  0  0  0  0  0]
 [ 5  6  3  7  8  9  1 10]
 [ 2  3 11  0  0  0  0  0]]
ERROR! Session/line number was not unique in database. History logging moved to new session 59
